language: java
sudo: false
jdk:
- openjdk7

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
# ensure we have ruby
- ruby --version
- gem install bundler
- bundle install
# fetch 3rd party apis and such
- git submodule update --init
- chmod +x ./gradlew

install: ./gradlew setupCIWorkspace -S

script:
- ./gradlew build
- bundle exec ./tools/split_jars.rb
- ls -la build/libs
- ls -la build/packages
- bundle exec ./tools/checksum_builds.rb | tee ./checksums.txt
- bundle exec ./tools/lang_check.rb

# Deploy the artifacts back to GitHub
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file_glob: true
  file:
  - "checksums.txt"
  - "build/libs/growthcraft-*-complete.jar"
  - "build/libs/growthcraft-*-api.jar"
  - "build/libs/growthcraft-*-deobf.jar"
  - "build/libs/growthcraft-*-javadoc.jar"
  - "build/libs/growthcraft-*-sources.jar"
  # separate jars
  - "build/packages/growthcraft-*-complete-*.jar"
  - "build/packages/growthcraft-*-deobf-*.jar"
  skip_cleanup: true
  on:
    tags: true
